/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import controller.docghi;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javafx.scene.input.KeyCode;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;
import model.quanlyxe;

/**
 *
 * @author Hiep
 */
public class NewJFrame extends javax.swing.JFrame {

    seach t;
    private docghi file;
    private ArrayList<quanlyxe> list;
    DefaultTableModel model;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        file = new docghi();
        list = file.docxe();

        initComponents();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) jTable1.getModel();
        H1();
    }

    public void H1() {
        model.setRowCount(0);
        for (quanlyxe s : list) {
            model.addRow(s.toObject());
        }
    }

    public void removeDataFromList() {
        int i = jTable1.getSelectedRow();
        quanlyxe s = list.get(i);
        list.remove(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbienso = new javax.swing.JTextField();
        txttenchuxe = new javax.swing.JTextField();
        txtmauxe = new javax.swing.JTextField();
        txtngaygui = new javax.swing.JTextField();
        bntadd = new javax.swing.JButton();
        bntedit = new javax.swing.JButton();
        bntdelete = new javax.swing.JButton();
        bntclose = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnsave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loaixe = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boxsapxep = new javax.swing.JComboBox<>();
        btntimkiem = new javax.swing.JButton();
        btnsapxep = new javax.swing.JButton();

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Biển số");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tên chủ xe");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Màu xe");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ngày gửi");

        txtbienso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtbienso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbiensoFocusLost(evt);
            }
        });
        txtbienso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbiensoActionPerformed(evt);
            }
        });

        txttenchuxe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtmauxe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtngaygui.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bntadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntadd.setText("Thêm");
        bntadd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntaddActionPerformed(evt);
            }
        });

        bntedit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntedit.setText("Sửa");
        bntedit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnteditActionPerformed(evt);
            }
        });

        bntdelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntdelete.setText("Xoá");
        bntdelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdeleteActionPerformed(evt);
            }
        });

        bntclose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntclose.setText("Thoát");
        bntclose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntcloseActionPerformed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreset.setText("Đặt lại");
        btnreset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Biển số", "Tên chủ xe", "Màu xe", "Loại xe", "Ngày gửi", "Thời gian nhập"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnsave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsave.setText("Lưu");
        btnsave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN XE GỬI T4");

        loaixe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loaixe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe đạp", "Xe máy", "Ô tô" }));
        loaixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaixeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Loại xe");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sắp xếp theo:");

        boxsapxep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxsapxep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo tên", "Theo loại xe" }));
        boxsapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxsapxepActionPerformed(evt);
            }
        });

        btntimkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btntimkiem.setText("Tìm kiếm");
        btntimkiem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        btnsapxep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsapxep.setText("Sắp xếp");
        btnsapxep.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsapxepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtmauxe)
                                    .addComponent(txttenchuxe)
                                    .addComponent(txtngaygui)
                                    .addComponent(txtbienso)
                                    .addComponent(loaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(23, 23, 23)
                                .addComponent(boxsapxep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsapxep, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btntimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bntadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bntedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bntdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bntclose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtbienso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntadd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttenchuxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntedit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtmauxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loaixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(bntdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtngaygui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(boxsapxep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem)
                    .addComponent(bntclose)
                    .addComponent(btnsapxep))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        txtbienso.setText("");
        txttenchuxe.setText("");
        txtmauxe.setText("");
        loaixe.setSelectedIndex(0);
        txtngaygui.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    private void bntaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntaddActionPerformed
        if (txtbienso.getText().length() != 0 && txttenchuxe.getText().length() != 0 && txtmauxe.getText().length() != 0 && txtngaygui.getText().length() != 0) {

            quanlyxe s = new quanlyxe();

            s.setBienso(txtbienso.getText());
            s.setTenchuxe(txttenchuxe.getText());
            s.setMauxe(txtmauxe.getText());
            s.setLoaixe(loaixe.getSelectedItem().toString());
            s.setNgaygui(txtngaygui.getText());

            list.add(s);
            file.ghixe(list);
            H1();

            txtbienso.setText("");
            txttenchuxe.setText("");
            txtmauxe.setText("");
            txtngaygui.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập đầy đủ thông tin!");
        }
    }//GEN-LAST:event_bntaddActionPerformed


    private void bntcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntcloseActionPerformed
        System.exit(0); //thoat chuong trinh
// TODO add your handling code here:
    }//GEN-LAST:event_bntcloseActionPerformed

    private void bntdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdeleteActionPerformed
        int i = jTable1.getSelectedRow();
        if (i > -1) {
            int x = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá hay không?");
            if (x == JOptionPane.YES_OPTION) {
                bntdelete.setText("Xoá");
                removeDataFromList();
                H1();
                file.ghixe(list);
            } else {
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Chọn 1 hàng trong bảng để xoá!");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_bntdeleteActionPerformed

    private void txtbiensoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbiensoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbiensoActionPerformed


    private void bnteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnteditActionPerformed
        // TODO add your handling code here: sua thong tin
        int r = jTable1.getSelectedRow();
        if (r > -1) {
            txtbienso.setText(model.getValueAt(r, 0).toString());
            txttenchuxe.setText(model.getValueAt(r, 1).toString());
            txtmauxe.setText(model.getValueAt(r, 2).toString());
            loaixe.setSelectedItem(model.getValueAt(r, 3).toString());
            txtngaygui.setText(model.getValueAt(r, 4).toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Chọn 1 hàng trong bảng để sửa!");
        }
    }//GEN-LAST:event_bnteditActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        int r = jTable1.getSelectedRow();
        if (r > -1) {
            list.remove(r);
            if (txtbienso.getText().length() != 0 && txttenchuxe.getText().length() != 0 && txtmauxe.getText().length() != 0 && txtngaygui.getText().length() != 0) {

                quanlyxe s = new quanlyxe();

                s.setBienso(txtbienso.getText());
                s.setTenchuxe(txttenchuxe.getText());
                s.setMauxe(txtmauxe.getText());
                s.setLoaixe(loaixe.getSelectedItem().toString());
                s.setNgaygui(txtngaygui.getText());

                if (r < list.size()) {
                    list.add(r, s);
                } else {
                    list.add(s);
                }

                file.ghixe(list);
                H1();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Hãy nhập đầy đủ thông tin");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Chọn 1 hàng để sửa rồi nhấn lưu!");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void loaixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaixeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loaixeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbiensoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbiensoFocusLost
        // TODO add your handling code here:
        //2so 1chu 4so
        if(this.isVisible()){
        String bienso = txtbienso.getText();
        String reg = "^\\d{2}\\w{1}\\d{5}$";
        if(bienso.length()>0){
        
        if((!bienso.matches(reg))){
            JOptionPane.showMessageDialog(rootPane, "Sai định dạng, mời nhập lại!");
            }
        }
            else{
                JOptionPane.showMessageDialog(rootPane, "Biển số không được để trống!");}}
    }//GEN-LAST:event_txtbiensoFocusLost

    private void boxsapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxsapxepActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_boxsapxepActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        t = new seach();
        t.setVisible(true);
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void btnsapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsapxepActionPerformed
        // TODO add your handling code here:
        int r = boxsapxep.getSelectedIndex();
        if(r ==0){
            Collections.sort(list, new Comparator<quanlyxe>() {
                @Override
                public int compare(quanlyxe t, quanlyxe t1) {
                    return t.getTenchuxe().substring(t.getTenchuxe().lastIndexOf(" "))
                    .compareTo(t1.getTenchuxe().substring(t1.getTenchuxe().lastIndexOf(" ")));
                }
            });
        }

        if(r ==1){
            Collections.sort(list, new Comparator<quanlyxe>() {
                @Override
                public int compare(quanlyxe t, quanlyxe t1) {
                    return t.getLoaixe().substring(t.getLoaixe().lastIndexOf(" "))
                    .compareTo(t1.getLoaixe().substring(t1.getLoaixe().lastIndexOf(" ")));
                }
            });
        }

        model.setRowCount(0);
        for(quanlyxe b: list)
        model.addRow(b.toObject());
        
    }//GEN-LAST:event_btnsapxepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntadd;
    private javax.swing.JButton bntclose;
    private javax.swing.JButton bntdelete;
    private javax.swing.JButton bntedit;
    private javax.swing.JComboBox<String> boxsapxep;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsapxep;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> loaixe;
    private javax.swing.JTextField txtbienso;
    private javax.swing.JTextField txtmauxe;
    private javax.swing.JTextField txtngaygui;
    private javax.swing.JTextField txttenchuxe;
    // End of variables declaration//GEN-END:variables

    
}
